Added main section of moblie version to html and css file
abiodunraheem/Portfolio-template2 pull request #2
Opened 2022-03-17 12:41 UTC by abiodunraheem

## Added main section of moblie version to html and css file

- I parse a Figma design to create a UI.
- Used Flexbox to place elements in the page.
- I used CSS Grid to place elements in the page.
- I Built a personal portfolio site using a mobile first approach.

2022-03-17 13:10 UTC, AnselemOdims requested changes
### Hi @abiodunraheem, 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-17 13:10 UTC, AnselemOdims commented on index.html
> +                <div class="section-image"></div>
- [ ] Please make sure the image for this card is added using the `img` tag

2022-03-17 13:10 UTC, AnselemOdims commented on index.html
> +                        <textarea name="Enter-text" id="enter-text" cols="41" rows="5" placeholder="Enter text here" maxlength="500" required></textarea>
- [ ] Please remove this section as it is not needed to complete this milestone. It will be required in the upcoming milestones

2022-03-17 13:10 UTC, AnselemOdims commented on index.html
> +                <div class="AbiodunHeader">
- [ ] [OPTIONAL] It is best practice to name your CSS class name in lowercase

2022-03-18 07:58 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @abiodunraheem👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 08:23 UTC, merged