Media query added to design desktop section
abiodunraheem/Portfolio-template2 pull request #4
Opened 2022-03-23 08:56 UTC by abiodunraheem

## Media query added to design desktop section

- I  parse a Figma design to create a UI.
- I created UIs adaptable to different screen sizes using media queries.

2022-03-23 09:39 UTC, CollinsTatang requested changes
Hi @abiodunraheem, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] Please fix your social media icons
### **Take a Look**
![your-social](https://user-images.githubusercontent.com/55596970/159669129-ee2192cd-3bc7-446e-b700-ce2ad19fe016.png)

### **See the figmal design**
![figmal-social](https://user-images.githubusercontent.com/55596970/159669057-87d55087-5304-44d1-8be9-4bc0469e2dbd.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 09:39 UTC, CollinsTatang commented on index.html
> +       </main>
- [ ] Please check these lines of code only one item display and try to follow the figmal design 
### **Take a Look **
![your-car](https://user-images.githubusercontent.com/55596970/159666970-6c5163a7-5891-46d9-a103-ef5ff3c742bb.png)
### **Check figmal Design**
![figma-cart](https://user-images.githubusercontent.com/55596970/159667233-66675960-bec6-4364-a089-f05361a8b0f6.png)

2022-03-24 20:14 UTC, closed without merging

2022-03-24 23:21 UTC, MeqdamAlqudah reviewed
Hi @abiodunraheem , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-03-24 23:21 UTC, MeqdamAlqudah commented on index.html
> +                  <li class="projectRuby">
- [ ] Please make sure that all the projects are appearing on the screen and make sure they looks exactly like Figma design 
![image](https://user-images.githubusercontent.com/74744787/160024544-31e1ec50-ecf8-4a8a-8a0a-22e7a65417b7.png)

![image](https://user-images.githubusercontent.com/74744787/160024575-dbc25529-28fe-41ab-ad1a-f26ded68d5f8.png)

I think the problem here comes from the quires make sure that you are using them correctly 
![image](https://user-images.githubusercontent.com/74744787/160024698-3304619b-11f8-42bb-8e13-d078010f07bf.png)

2022-03-24 23:21 UTC, MeqdamAlqudah commented on index.html
> +            <div class="image-1">
- [ ] Please make sure that your mobile version still work even after I change back to it 
I think this problem comes from media queries used poorly, also make sure to 
![image](https://user-images.githubusercontent.com/74744787/160025268-42aa05ac-e6bb-44a8-bd7d-1f93adf500b2.png)

2022-03-24 23:21 UTC, MeqdamAlqudah commented on index.html
> +                <li class="grid-item4"><a href="#">Ruby</a></li>
- [ ] Please make sure to align the navigation links exactly as Figma design i.e fix the distance between the links in Figma design there is more margin between the links

![image](https://user-images.githubusercontent.com/74744787/160025388-ecaa7a7a-f7ea-41f3-8c08-91eb4bb5d2ca.png)

![image](https://user-images.githubusercontent.com/74744787/160025482-049689c7-adf5-4552-90ca-57f1b7b0e471.png)